version: "3"
services:
  project-name:
    build: .
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - '9691:9691'
    networks:
      - network-project-name-dev
    command: [ "npm", "run", "startDev"]
networks:
  network-project-name-dev:

